apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: quay.io/eduk8s-labs/app-k8s-fundamentals-frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: BLOG_SITE_NAME
          value: EduK8S Blog
