apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  labels:
    app: blog
spec:
  rules:
  - host: blog-springone-w01-s1703.apps.asdf1.tanzu-devs.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: blog
          servicePort: 8080
