apiVersion: v1
kind: Service
metadata:
  name: blog-db
  labels:
    app: blog-db
spec:
  type: ClusterIP
  selector:
    app: blog-db
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
